const productList = [
  {
    category: 'clothesAndShoes',
    products: [
      {
        'id': 1,
        'name': 'Кроссовки Nike',
        'description': 'Удобные кроссовки для повседневной носки',
        'category': 'clothesAndShoes',
        'price': 5999,
        'quantityOfGoods': 10,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 2,
        'name': 'Куртка зимняя',
        'description': 'Теплая куртка с подкладкой',
        'category': 'clothesAndShoes',
        'price': 8999,
        'quantityOfGoods': 7,
        'productRating': 4.8,
        'image': 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 3,
        'name': 'Футболка белая',
        'description': 'Хлопковая футболка',
        'category': 'clothesAndShoes',
        'price': 799,
        'quantityOfGoods': 50,
        'productRating': 4.2,
        'image': 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 4,
        'name': 'Джинсы мужские',
        'description': 'Классические джинсы',
        'category': 'clothesAndShoes',
        'price': 2999,
        'quantityOfGoods': 20,
        'productRating': 4.4,
        'image': 'https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 5,
        'name': 'Ботинки кожаные',
        'description': 'Натуральная кожа, зимние',
        'category': 'clothesAndShoes',
        'price': 6999,
        'quantityOfGoods': 5,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
    ]
  },
  {
    category: 'householdGoods',
    products: [
      {
        'id': 6,
        'name': 'Швабра с отжимом',
        'description': 'Для удобной уборки пола',
        'category': 'householdGoods',
        'price': 1299,
        'quantityOfGoods': 12,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Швабра+с+отжимом',
      },
      {
        'id': 7,
        'name': 'Набор губок',
        'description': '5 штук для мытья посуды',
        'category': 'householdGoods',
        'price': 199,
        'quantityOfGoods': 100,
        'productRating': 4.1,
        'image': 'https://via.placeholder.com/500?text=Набор+губок',
      },
      {
        'id': 8,
        'name': 'Корзина для белья',
        'description': 'Пластиковая корзина 45л',
        'category': 'householdGoods',
        'price': 899,
        'quantityOfGoods': 15,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Корзина+для+белья',
      },
      {
        'id': 9,
        'name': 'Контейнеры для хранения',
        'description': 'Набор из 3 контейнеров',
        'category': 'householdGoods',
        'price': 499,
        'quantityOfGoods': 25,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Контейнеры+для+хранения',
      },
      {
        'id': 10,
        'name': 'Сушилка для белья',
        'description': 'Складная сушилка, 20м',
        'category': 'householdGoods',
        'price': 1799,
        'quantityOfGoods': 8,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Сушилка+для+белья',
      },
    ]
  },
  {
    category: 'electronics',
    products: [
      {
        'id': 11,
        'name': 'Смартфон Samsung',
        'description': '128Гб, черный',
        'category': 'electronics',
        'price': 25999,
        'quantityOfGoods': 30,
        'productRating': 4.8,
        'image': 'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 12,
        'name': 'Наушники Bluetooth',
        'description': 'Беспроводные с шумоподавлением',
        'category': 'electronics',
        'price': 3999,
        'quantityOfGoods': 50,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 13,
        'name': 'Повербанк 10000мАч',
        'description': 'Компактный и мощный',
        'category': 'electronics',
        'price': 1499,
        'quantityOfGoods': 80,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Повербанк+10000мАч',
      },
      {
        'id': 14,
        'name': 'Монитор 24"',
        'description': 'FullHD монитор',
        'category': 'electronics',
        'price': 7499,
        'quantityOfGoods': 18,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1546538915-a9e2c8d0a8e6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 15,
        'name': 'Клавиатура механическая',
        'description': 'RGB подсветка',
        'category': 'electronics',
        'price': 2999,
        'quantityOfGoods': 25,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
    ]
  },
  {
    category: 'householdAppliances',
    products: [
      {
        'id': 16,
        'name': 'Микроволновка',
        'description': '20л, с грилем',
        'category': 'householdAppliances',
        'price': 5999,
        'quantityOfGoods': 10,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 17,
        'name': 'Пылесос циклонный',
        'description': 'Мощный и компактный',
        'category': 'householdAppliances',
        'price': 7999,
        'quantityOfGoods': 8,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Пылесос+циклонный',
      },
      {
        'id': 18,
        'name': 'Утюг с паром',
        'description': 'Быстрый нагрев',
        'category': 'householdAppliances',
        'price': 2499,
        'quantityOfGoods': 15,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Утюг+с+паром',
      },
      {
        'id': 19,
        'name': 'Хлебопечка',
        'description': '12 программ, таймер',
        'category': 'householdAppliances',
        'price': 5999,
        'quantityOfGoods': 6,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Хлебопечка',
      },
      {
        'id': 20,
        'name': 'Электрочайник',
        'description': '1.7л, автоотключение',
        'category': 'householdAppliances',
        'price': 1999,
        'quantityOfGoods': 20,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1606755456206-b25206bfa433?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
    ]
  },
  {
    category: 'goodsForChildren',
    products: [
      {
        'id': 21,
        'name': 'Коляска прогулочная',
        'description': 'Легкая и складная',
        'category': 'goodsForChildren',
        'price': 8999,
        'quantityOfGoods': 5,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1564078516393-cf04bd966897?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 22,
        'name': 'Пеленки одноразовые',
        'description': '60x60, упаковка 30шт',
        'category': 'goodsForChildren',
        'price': 799,
        'quantityOfGoods': 40,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Пеленки+одноразовые',
      },
      {
        'id': 23,
        'name': 'Игрушка развивающая',
        'description': 'Музыкальная с огоньками',
        'category': 'goodsForChildren',
        'price': 1499,
        'quantityOfGoods': 20,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 24,
        'name': 'Стульчик для кормления',
        'description': 'Съемный поднос, компактный',
        'category': 'goodsForChildren',
        'price': 3999,
        'quantityOfGoods': 10,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Стульчик+для+кормления',
      },
      {
        'id': 25,
        'name': 'Ночник детский',
        'description': 'Проектор звездного неба',
        'category': 'goodsForChildren',
        'price': 999,
        'quantityOfGoods': 30,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Ночник+детский',
      },
    ]
  },
  {
    category: 'constructionAndRenovation',
    products: [
      {
        'id': 26,
        'name': 'Перфоратор Bosch',
        'description': 'Мощный инструмент для ремонта',
        'category': 'constructionAndRenovation',
        'price': 9999,
        'quantityOfGoods': 12,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 27,
        'name': 'Обои виниловые',
        'description': 'Рулон 10м, с узором',
        'category': 'constructionAndRenovation',
        'price': 599,
        'quantityOfGoods': 40,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Обои+виниловые',
      },
      {
        'id': 28,
        'name': 'Краска интерьерная',
        'description': '10л, белая',
        'category': 'constructionAndRenovation',
        'price': 1299,
        'quantityOfGoods': 30,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Краска+интерьерная',
      },
      {
        'id': 29,
        'name': 'Плитка керамическая',
        'description': '20x20, упаковка 1.2м²',
        'category': 'constructionAndRenovation',
        'price': 899,
        'quantityOfGoods': 50,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Плитка+керамическая',
      },
      {
        'id': 30,
        'name': 'Герметик силиконовый',
        'description': 'Белый, тюбик 300мл',
        'category': 'constructionAndRenovation',
        'price': 299,
        'quantityOfGoods': 60,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Герметик+силиконовый',
      },
    ]
  },
  {
    category: 'furniture',
    products: [
      {
        'id': 31,
        'name': 'Стол письменный',
        'description': 'Деревянный, 120x60 см',
        'category': 'furniture',
        'price': 5999,
        'quantityOfGoods': 10,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 32,
        'name': 'Кресло офисное',
        'description': 'Эргономичное с поддержкой поясницы',
        'category': 'furniture',
        'price': 4999,
        'quantityOfGoods': 8,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 33,
        'name': 'Шкаф 3-дверный',
        'description': 'Белый, с зеркалом и полками',
        'category': 'furniture',
        'price': 10999,
        'quantityOfGoods': 5,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 34,
        'name': 'Кровать двуспальная',
        'description': '160x200 см, деревянное основание',
        'category': 'furniture',
        'price': 8999,
        'quantityOfGoods': 7,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 35,
        'name': 'Тумбочка прикроватная',
        'description': 'С 2 ящиками, цвет орех',
        'category': 'furniture',
        'price': 2499,
        'quantityOfGoods': 12,
        'productRating': 4.4,
        'image': 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 36,
        'name': 'Диван угловой',
        'description': 'Прямоугольный, тканевая обивка',
        'category': 'furniture',
        'price': 24999,
        'quantityOfGoods': 4,
        'productRating': 4.8,
        'image': 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 37,
        'name': 'Комод 4-х ящичный',
        'description': 'Белый глянцевый, 80 см ширина',
        'category': 'furniture',
        'price': 6599,
        'quantityOfGoods': 6,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1567538096611-e5117e8a0b4a?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 38,
        'name': 'Стул барный',
        'description': 'Металлическая основа, регулируемая высота',
        'category': 'furniture',
        'price': 3299,
        'quantityOfGoods': 9,
        'productRating': 4.3,
        'image': 'https://images.unsplash.com/photo-1592078615290-033ee584e267?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 39,
        'name': 'Стеллаж книжный',
        'description': '5 полок, сосна',
        'category': 'furniture',
        'price': 4899,
        'quantityOfGoods': 11,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 40,
        'name': 'Журнальный столик',
        'description': 'Стеклянная столешница, металлические ножки',
        'category': 'furniture',
        'price': 3799,
        'quantityOfGoods': 8,
        'productRating': 4.4,
        'image': 'https://images.unsplash.com/photo-1564429090690-a6e4894c2933?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 41,
        'name': 'Матрас ортопедический',
        'description': '160x200 см, кокосовая койра',
        'category': 'furniture',
        'price': 12999,
        'quantityOfGoods': 5,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 42,
        'name': 'Пуф круглый',
        'description': 'Кожзам, диаметр 45 см',
        'category': 'furniture',
        'price': 1899,
        'quantityOfGoods': 15,
        'productRating': 4.2,
        'image': 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 43,
        'name': 'Стол обеденный',
        'description': 'Круглый, диаметр 110 см',
        'category': 'furniture',
        'price': 8999,
        'quantityOfGoods': 7,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 44,
        'name': 'Стул детский',
        'description': 'Регулируемый по высоте',
        'category': 'furniture',
        'price': 1599,
        'quantityOfGoods': 20,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 45,
        'name': 'Зеркало напольное',
        'description': '180x60 см, деревянная рама',
        'category': 'furniture',
        'price': 4599,
        'quantityOfGoods': 9,
        'productRating': 4.4,
        'image': 'https://images.unsplash.com/photo-1558403194-611308249627?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 46,
        'name': 'Шкаф-купе 2-х створчатый',
        'description': 'Глубина 60 см, система "Командор"',
        'category': 'furniture',
        'price': 15999,
        'quantityOfGoods': 4,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 47,
        'name': 'Тумба под TV',
        'description': '120 см, с открытыми полками',
        'category': 'furniture',
        'price': 5999,
        'quantityOfGoods': 6,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 48,
        'name': 'Кресло-качалка',
        'description': 'Деревянное, с текстильной подушкой',
        'category': 'furniture',
        'price': 7999,
        'quantityOfGoods': 5,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1592078615290-033ee584e267?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 49,
        'name': 'Стол компьютерный',
        'description': 'Угловой, 140x140 см',
        'category': 'furniture',
        'price': 7599,
        'quantityOfGoods': 8,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 50,
        'name': 'Скамейка прихожая',
        'description': 'С ящиком для обуви, 80 см',
        'category': 'furniture',
        'price': 3499,
        'quantityOfGoods': 12,
        'productRating': 4.4,
        'image': 'https://images.unsplash.com/photo-1567538096631-e0c55bd6374c?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 51,
        'name': 'Стенка гостиная',
        'description': 'Модульная система, цвет венге',
        'category': 'furniture',
        'price': 28999,
        'quantityOfGoods': 3,
        'productRating': 4.8,
        'image': 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 52,
        'name': 'Вешалка напольная',
        'description': 'Металлическая, 5 крючков',
        'category': 'furniture',
        'price': 1299,
        'quantityOfGoods': 25,
        'productRating': 4.3,
        'image': 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
    ]
  },
  {
    category: 'pharmacy',
    products: [
      {
        'id': 53,
        'name': 'Парацетамол',
        'description': '500мг, 20 таблеток',
        'category': 'pharmacy',
        'price': 89,
        'quantityOfGoods': 100,
        'productRating': 4.8,
        'image': 'https://via.placeholder.com/500?text=Парацетамол',
      },
      {
        'id': 54,
        'name': 'Витамин C',
        'description': 'Аскорбиновая кислота, 100шт',
        'category': 'pharmacy',
        'price': 299,
        'quantityOfGoods': 50,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Витамин+C',
      },
      {
        'id': 55,
        'name': 'Термометр электронный',
        'description': 'Измерение за 10 секунд',
        'category': 'pharmacy',
        'price': 599,
        'quantityOfGoods': 20,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Термометр+электронный',
      },
      {
        'id': 56,
        'name': 'Пластырь бактерицидный',
        'description': '20 штук в упаковке',
        'category': 'pharmacy',
        'price': 129,
        'quantityOfGoods': 70,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Пластырь+бактерицидный',
      },
      {
        'id': 57,
        'name': 'Маска медицинская',
        'description': '50 штук, одноразовая',
        'category': 'pharmacy',
        'price': 399,
        'quantityOfGoods': 150,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Маска+медицинская',
      },
      {
        'id': 58,
        'name': 'Ибупрофен',
        'description': '200мг, 30 таблеток',
        'category': 'pharmacy',
        'price': 149,
        'quantityOfGoods': 80,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Ибупрофен',
      },
      {
        'id': 59,
        'name': 'Активированный уголь',
        'description': '250мг, 50 таблеток',
        'category': 'pharmacy',
        'price': 79,
        'quantityOfGoods': 120,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Активированный+уголь',
      },
      {
        'id': 60,
        'name': 'Називин',
        'description': 'Капли назальные 0.1%, 10мл',
        'category': 'pharmacy',
        'price': 189,
        'quantityOfGoods': 60,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Називин',
      },
      {
        'id': 61,
        'name': 'Нурофен',
        'description': 'Гель 5%, 100г',
        'category': 'pharmacy',
        'price': 349,
        'quantityOfGoods': 40,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Нурофен',
      },
      {
        'id': 62,
        'name': 'Валидол',
        'description': '60 таблеток под язык',
        'category': 'pharmacy',
        'price': 99,
        'quantityOfGoods': 90,
        'productRating': 4.0,
        'image': 'https://via.placeholder.com/500?text=Валидол',
      },
      {
        'id': 63,
        'name': 'Супрастин',
        'description': '25мг, 20 таблеток',
        'category': 'pharmacy',
        'price': 199,
        'quantityOfGoods': 55,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Супрастин',
      },
      {
        'id': 64,
        'name': 'Левомеколь',
        'description': 'Мазь 40г',
        'category': 'pharmacy',
        'price': 129,
        'quantityOfGoods': 65,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Левомеколь',
      },
      {
        'id': 65,
        'name': 'Корвалол',
        'description': '25мл, капли',
        'category': 'pharmacy',
        'price': 89,
        'quantityOfGoods': 75,
        'productRating': 4.1,
        'image': 'https://via.placeholder.com/500?text=Корвалол',
      },
      {
        'id': 66,
        'name': 'Бинт стерильный',
        'description': '5м x 10см',
        'category': 'pharmacy',
        'price': 59,
        'quantityOfGoods': 200,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Бинт+стерильный',
      },
      {
        'id': 67,
        'name': 'Зеленка',
        'description': 'Раствор 1%, 10мл',
        'category': 'pharmacy',
        'price': 49,
        'quantityOfGoods': 110,
        'productRating': 4.0,
        'image': 'https://via.placeholder.com/500?text=Зеленка',
      },
      {
        'id': 68,
        'name': 'Перекись водорода',
        'description': '3%, 100мл',
        'category': 'pharmacy',
        'price': 39,
        'quantityOfGoods': 95,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Перекись+водорода',
      },
      {
        'id': 69,
        'name': 'Аспирин',
        'description': '500мг, 10 таблеток',
        'category': 'pharmacy',
        'price': 79,
        'quantityOfGoods': 85,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Аспирин',
      },
      {
        'id': 70,
        'name': 'Глицин',
        'description': '100мг, 50 таблеток',
        'category': 'pharmacy',
        'price': 119,
        'quantityOfGoods': 70,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Глицин',
      },
      {
        'id': 71,
        'name': 'Цитрамон',
        'description': '20 таблеток',
        'category': 'pharmacy',
        'price': 69,
        'quantityOfGoods': 60,
        'productRating': 4.1,
        'image': 'https://via.placeholder.com/500?text=Цитрамон',
      },
      {
        'id': 72,
        'name': 'Фурацилин',
        'description': '10 таблеток',
        'category': 'pharmacy',
        'price': 59,
        'quantityOfGoods': 45,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Фурацилин',
      },
      {
        'id': 73,
        'name': 'Бепантен',
        'description': 'Мазь 30г',
        'category': 'pharmacy',
        'price': 499,
        'quantityOfGoods': 30,
        'productRating': 4.8,
        'image': 'https://via.placeholder.com/500?text=Бепантен',
      },
      {
        'id': 74,
        'name': 'Смекта',
        'description': '10 пакетиков',
        'category': 'pharmacy',
        'price': 249,
        'quantityOfGoods': 50,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Смекта',
      },
      {
        'id': 75,
        'name': 'Линекс',
        'description': '16 капсул',
        'category': 'pharmacy',
        'price': 399,
        'quantityOfGoods': 40,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Линекс',
      },
      {
        'id': 76,
        'name': 'Но-шпа',
        'description': '40мг, 100 таблеток',
        'category': 'pharmacy',
        'price': 299,
        'quantityOfGoods': 35,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Но-шпа',
      },
      {
        'id': 77,
        'name': 'Мезим',
        'description': '20 таблеток',
        'category': 'pharmacy',
        'price': 199,
        'quantityOfGoods': 55,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Мезим',
      },
      {
        'id': 78,
        'name': 'Эссенциале',
        'description': '30 капсул',
        'category': 'pharmacy',
        'price': 699,
        'quantityOfGoods': 25,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Эссенциале',
      },
      {
        'id': 79,
        'name': 'Лазолван',
        'description': 'Сироп 100мл',
        'category': 'pharmacy',
        'price': 349,
        'quantityOfGoods': 30,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Лазолван',
      },
      {
        'id': 80,
        'name': 'Амбробене',
        'description': '30мг, 20 таблеток',
        'category': 'pharmacy',
        'price': 199,
        'quantityOfGoods': 40,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Амбробене',
      },
      {
        'id': 81,
        'name': 'Отипакс',
        'description': 'Капли ушные 16г',
        'category': 'pharmacy',
        'price': 299,
        'quantityOfGoods': 20,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Отипакс',
      },
      {
        'id': 82,
        'name': 'Нафтизин',
        'description': 'Капли 0.1%, 15мл',
        'category': 'pharmacy',
        'price': 49,
        'quantityOfGoods': 65,
        'productRating': 4.0,
        'image': 'https://via.placeholder.com/500?text=Нафтизин',
      },
      {
        'id': 83,
        'name': 'Визин',
        'description': 'Капли глазные 15мл',
        'category': 'pharmacy',
        'price': 249,
        'quantityOfGoods': 30,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Визин',
      },
      {
        'id': 84,
        'name': 'Тонометр механический',
        'description': 'С фонендоскопом',
        'category': 'pharmacy',
        'price': 899,
        'quantityOfGoods': 15,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Тонометр+механический',
      },
      {
        'id': 85,
        'name': 'Гексорал',
        'description': 'Спрей 40мл',
        'category': 'pharmacy',
        'price': 279,
        'quantityOfGoods': 35,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Гексорал',
      },
      {
        'id': 86,
        'name': 'Стрепсилс',
        'description': '24 пастилки',
        'category': 'pharmacy',
        'price': 249,
        'quantityOfGoods': 45,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Стрепсилс',
      },
      {
        'id': 87,
        'name': 'Фарингосепт',
        'description': '20 таблеток',
        'category': 'pharmacy',
        'price': 149,
        'quantityOfGoods': 50,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Фарингосепт',
      },
      {
        'id': 88,
        'name': 'Мирамистин',
        'description': 'Раствор 150мл',
        'category': 'pharmacy',
        'price': 349,
        'quantityOfGoods': 30,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Мирамистин',
      },
      {
        'id': 89,
        'name': 'Хлоргексидин',
        'description': 'Раствор 0.05%, 100мл',
        'category': 'pharmacy',
        'price': 49,
        'quantityOfGoods': 80,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Хлоргексидин',
      },
      {
        'id': 90,
        'name': 'Пантенол',
        'description': 'Спрей 130г',
        'category': 'pharmacy',
        'price': 299,
        'quantityOfGoods': 40,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Пантенол',
      },
      {
        'id': 91,
        'name': 'Дексаметазон',
        'description': 'Глазные капли 10мл',
        'category': 'pharmacy',
        'price': 119,
        'quantityOfGoods': 25,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Дексаметазон',
      },
      {
        'id': 92,
        'name': 'Цинковая мазь',
        'description': '30г',
        'category': 'pharmacy',
        'price': 69,
        'quantityOfGoods': 60,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Цинковая+мазь',
      },
      {
        'id': 93,
        'name': 'Граммидин',
        'description': '18 таблеток',
        'category': 'pharmacy',
        'price': 279,
        'quantityOfGoods': 35,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Граммидин',
      },
      {
        'id': 94,
        'name': 'Каметон',
        'description': 'Спрей 30г',
        'category': 'pharmacy',
        'price': 129,
        'quantityOfGoods': 50,
        'productRating': 4.1,
        'image': 'https://via.placeholder.com/500?text=Каметон',
      },
      {
        'id': 95,
        'name': 'Витаон',
        'description': 'Масло 50мл',
        'category': 'pharmacy',
        'price': 199,
        'quantityOfGoods': 30,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Витаон',
      },
      {
        'id': 96,
        'name': 'Борная кислота',
        'description': '10г порошок',
        'category': 'pharmacy',
        'price': 39,
        'quantityOfGoods': 70,
        'productRating': 4.0,
        'image': 'https://via.placeholder.com/500?text=Борная+кислота',
      },
      {
        'id': 97,
        'name': 'Йод',
        'description': 'Раствор 5%, 10мл',
        'category': 'pharmacy',
        'price': 29,
        'quantityOfGoods': 100,
        'productRating': 4.1,
        'image': 'https://via.placeholder.com/500?text=Йод',
      },
      {
        'id': 98,
        'name': 'Бинт эластичный',
        'description': '5м x 8см',
        'category': 'pharmacy',
        'price': 89,
        'quantityOfGoods': 45,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Бинт+эластичный',
      },
      {
        'id': 99,
        'name': 'Вата медицинская',
        'description': '100г стерильная',
        'category': 'pharmacy',
        'price': 59,
        'quantityOfGoods': 120,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Вата+медицинская',
      },
      {
        'id': 100,
        'name': 'Салфетки спиртовые',
        'description': '100 штук в упаковке',
        'category': 'pharmacy',
        'price': 99,
        'quantityOfGoods': 80,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Салфетки+спиртовые',
      },
      {
        'id': 101,
        'name': 'Глюкометр',
        'description': 'С набором тест-полосок',
        'category': 'pharmacy',
        'price': 1299,
        'quantityOfGoods': 10,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Глюкометр',
      },
      {
        'id': 102,
        'name': 'Терафлю',
        'description': '10 пакетиков',
        'category': 'pharmacy',
        'price': 399,
        'quantityOfGoods': 30,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Терафлю',
      },
    ]
  },
  {
    category: 'hobbiesAndCreativity',
    products: [
      {
        'id': 103,
        'name': 'Набор для рисования',
        'description': 'Краски, кисти, холст',
        'category': 'hobbiesAndCreativity',
        'price': 1499,
        'quantityOfGoods': 25,
        'productRating': 4.7,
        'image': 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 104,
        'name': 'Конструктор Lego',
        'description': '500 деталей, классика',
        'category': 'hobbiesAndCreativity',
        'price': 3499,
        'quantityOfGoods': 15,
        'productRating': 4.9,
        'image': 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 105,
        'name': 'Пряжа для вязания',
        'description': '100% шерсть, 3 мотка',
        'category': 'hobbiesAndCreativity',
        'price': 599,
        'quantityOfGoods': 40,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1610392983074-dc0b5d93a0c4?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 106,
        'name': 'Электрогитара',
        'description': 'Для начинающих',
        'category': 'hobbiesAndCreativity',
        'price': 8999,
        'quantityOfGoods': 6,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 107,
        'name': 'Мольберт деревянный',
        'description': 'Настольный, складной',
        'category': 'hobbiesAndCreativity',
        'price': 1299,
        'quantityOfGoods': 10,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Мольберт+деревянный',
      },
      {
        'id': 108,
        'name': 'Набор для вышивания',
        'description': 'Схема, нитки, иглы',
        'category': 'hobbiesAndCreativity',
        'price': 799,
        'quantityOfGoods': 20,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1593644311514-03a9cd5f18a9?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 109,
        'name': 'Гончарный круг',
        'description': 'Электрический, 30 см',
        'category': 'hobbiesAndCreativity',
        'price': 5999,
        'quantityOfGoods': 5,
        'productRating': 4.8,
        'image': 'https://via.placeholder.com/500?text=Гончарный+круг',
      },
      {
        'id': 110,
        'name': 'Набор масляных красок',
        'description': '12 цветов, 40 мл',
        'category': 'hobbiesAndCreativity',
        'price': 1499,
        'quantityOfGoods': 18,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Набор+масляных+красок',
      },
      {
        'id': 111,
        'name': 'Скейтборд',
        'description': 'Профессиональный, 80 см',
        'category': 'hobbiesAndCreativity',
        'price': 3999,
        'quantityOfGoods': 8,
        'productRating': 4.5,
        'image': 'https://images.unsplash.com/photo-1572776685600-aca8c3456337?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 112,
        'name': '3D-ручка',
        'description': 'С LCD дисплеем',
        'category': 'hobbiesAndCreativity',
        'price': 2499,
        'quantityOfGoods': 12,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=3D-ручка',
      },
      {
        'id': 113,
        'name': 'Набор для бисероплетения',
        'description': '5000 бусин, схемы',
        'category': 'hobbiesAndCreativity',
        'price': 899,
        'quantityOfGoods': 30,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Набор+для+бисероплетения',
      },
      {
        'id': 114,
        'name': 'Дроны для начинающих',
        'description': 'С камерой 720p',
        'category': 'hobbiesAndCreativity',
        'price': 4999,
        'quantityOfGoods': 7,
        'productRating': 4.6,
        'image': 'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 115,
        'name': 'Набор для мыловарения',
        'description': '10 форм, красители',
        'category': 'hobbiesAndCreativity',
        'price': 1299,
        'quantityOfGoods': 15,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Набор+для+мыловарения',
      },
      {
        'id': 116,
        'name': 'Акварельные карандаши',
        'description': '36 цветов',
        'category': 'hobbiesAndCreativity',
        'price': 899,
        'quantityOfGoods': 22,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Акварельные+карандаши',
      },
      {
        'id': 117,
        'name': 'Металлоискатель',
        'description': 'Глубина до 1.5 м',
        'category': 'hobbiesAndCreativity',
        'price': 6999,
        'quantityOfGoods': 4,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Металлоискатель',
      },
      {
        'id': 118,
        'name': 'Набор для лепки',
        'description': 'Полимерная глина, 12 цветов',
        'category': 'hobbiesAndCreativity',
        'price': 799,
        'quantityOfGoods': 25,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Набор+для+лепки',
      },
      {
        'id': 119,
        'name': 'Фотоаппарат моментальной печати',
        'description': 'С 20 кадрами',
        'category': 'hobbiesAndCreativity',
        'price': 3499,
        'quantityOfGoods': 9,
        'productRating': 4.8,
        'image': 'https://images.unsplash.com/photo-1520390138845-fd2d229dd553?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      },
      {
        'id': 120,
        'name': 'Набор для выжигания',
        'description': 'Доска, прибор, узоры',
        'category': 'hobbiesAndCreativity',
        'price': 1499,
        'quantityOfGoods': 14,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Набор+для+выжигания',
      },
      {
        'id': 121,
        'name': 'Микроскоп',
        'description': 'Увеличение 1000x',
        'category': 'hobbiesAndCreativity',
        'price': 2999,
        'quantityOfGoods': 11,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Микроскоп',
      },
      {
        'id': 122,
        'name': 'Набор для гравировки',
        'description': '10 насадок, инструкция',
        'category': 'hobbiesAndCreativity',
        'price': 1999,
        'quantityOfGoods': 8,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Набор+для+гравировки',
      },
      {
        'id': 123,
        'name': 'Пастель сухая',
        'description': '48 цветов',
        'category': 'hobbiesAndCreativity',
        'price': 1299,
        'quantityOfGoods': 17,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Пастель+сухая',
      },
      {
        'id': 124,
        'name': 'Набор для фокусов',
        'description': '50 трюков',
        'category': 'hobbiesAndCreativity',
        'price': 899,
        'quantityOfGoods': 20,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Набор+для+фокусов',
      },
      {
        'id': 125,
        'name': 'Модель для сборки',
        'description': 'Корабль, 1:100',
        'category': 'hobbiesAndCreativity',
        'price': 1999,
        'quantityOfGoods': 12,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Модель+для+сборки',
      },
      {
        'id': 126,
        'name': 'Набор для каллиграфии',
        'description': 'Перья, тушь, прописи',
        'category': 'hobbiesAndCreativity',
        'price': 1599,
        'quantityOfGoods': 15,
        'productRating': 4.8,
        'image': 'https://via.placeholder.com/500?text=Набор+для+каллиграфии',
      },
      {
        'id': 127,
        'name': 'Термомозаика',
        'description': '5000 бусин, 10 схем',
        'category': 'hobbiesAndCreativity',
        'price': 699,
        'quantityOfGoods': 28,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Термомозаика',
      },
      {
        'id': 128,
        'name': 'Набор для создания украшений',
        'description': 'Бусины, фурнитура',
        'category': 'hobbiesAndCreativity',
        'price': 1199,
        'quantityOfGoods': 19,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Набор+для+создания+украшений',
      },
      {
        'id': 129,
        'name': 'Аэрохоккей',
        'description': 'Домашний, 120 см',
        'category': 'hobbiesAndCreativity',
        'price': 4999,
        'quantityOfGoods': 6,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Аэрохоккей',
      },
      {
        'id': 130,
        'name': 'Набор для эбру',
        'description': 'Краски, лоток, бумага',
        'category': 'hobbiesAndCreativity',
        'price': 1799,
        'quantityOfGoods': 13,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Набор+для+эбру',
      },
      {
        'id': 131,
        'name': 'Гравюра',
        'description': 'Набор с золотым покрытием',
        'category': 'hobbiesAndCreativity',
        'price': 599,
        'quantityOfGoods': 24,
        'productRating': 4.1,
        'image': 'https://via.placeholder.com/500?text=Гравюра',
      },
      {
        'id': 132,
        'name': 'Набор для плетения',
        'description': 'Макраме, 5 схем',
        'category': 'hobbiesAndCreativity',
        'price': 899,
        'quantityOfGoods': 18,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Набор+для+плетения',
      },
      {
        'id': 133,
        'name': 'Модель солнечной системы',
        'description': 'Светящаяся, 30 см',
        'category': 'hobbiesAndCreativity',
        'price': 2499,
        'quantityOfGoods': 9,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Модель+солнечной+системы',
      },
      {
        'id': 134,
        'name': 'Набор для выпиливания',
        'description': 'Лобзик, фанера, схемы',
        'category': 'hobbiesAndCreativity',
        'price': 1599,
        'quantityOfGoods': 11,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Набор+для+выпиливания',
      },
      {
        'id': 135,
        'name': 'Картины по номерам',
        'description': '40x50 см, 24 цвета',
        'category': 'hobbiesAndCreativity',
        'price': 999,
        'quantityOfGoods': 22,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Картины+по+номерам',
      },
      {
        'id': 136,
        'name': 'Набор для флорариума',
        'description': 'Стекло, растения, грунт',
        'category': 'hobbiesAndCreativity',
        'price': 1999,
        'quantityOfGoods': 14,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Набор+для+флорариума',
      },
      {
        'id': 137,
        'name': 'Кинетический песок',
        'description': '1 кг, 4 цвета',
        'category': 'hobbiesAndCreativity',
        'price': 799,
        'quantityOfGoods': 30,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Кинетический+песок',
      },
      {
        'id': 138,
        'name': 'Набор для декупажа',
        'description': 'Салфетки, клей, лак',
        'category': 'hobbiesAndCreativity',
        'price': 699,
        'quantityOfGoods': 25,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Набор+для+декупажа',
      },
      {
        'id': 139,
        'name': 'Планшет для рисования',
        'description': 'Электронный, 10 дюймов',
        'category': 'hobbiesAndCreativity',
        'price': 3499,
        'quantityOfGoods': 8,
        'productRating': 4.8,
        'image': 'https://via.placeholder.com/500?text=Планшет+для+рисования',
      },
      {
        'id': 140,
        'name': 'Набор для оригами',
        'description': '100 листов, схемы',
        'category': 'hobbiesAndCreativity',
        'price': 499,
        'quantityOfGoods': 35,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Набор+для+оригами',
      },
      {
        'id': 141,
        'name': 'Сборная модель танка',
        'description': '1:35, пластик',
        'category': 'hobbiesAndCreativity',
        'price': 1299,
        'quantityOfGoods': 16,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Сборная+модель+танка',
      },
      {
        'id': 142,
        'name': 'Набор для валяния',
        'description': 'Шерсть, иглы, форма',
        'category': 'hobbiesAndCreativity',
        'price': 899,
        'quantityOfGoods': 20,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Набор+для+валяния',
      },
      {
        'id': 143,
        'name': 'Мозаика алмазная',
        'description': '40x50 см, полный набор',
        'category': 'hobbiesAndCreativity',
        'price': 1499,
        'quantityOfGoods': 12,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Мозаика+алмазная',
      },
      {
        'id': 144,
        'name': 'Набор для пэчворка',
        'description': 'Ткань, схемы, инструменты',
        'category': 'hobbiesAndCreativity',
        'price': 1799,
        'quantityOfGoods': 10,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Набор+для+пэчворка',
      },
      {
        'id': 145,
        'name': 'Скетчбук',
        'description': 'А4, 100 листов',
        'category': 'hobbiesAndCreativity',
        'price': 599,
        'quantityOfGoods': 40,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Скетчбук',
      },
      {
        'id': 146,
        'name': 'Набор для росписи',
        'description': 'Керамика, краски',
        'category': 'hobbiesAndCreativity',
        'price': 1299,
        'quantityOfGoods': 15,
        'productRating': 4.6,
        'image': 'https://via.placeholder.com/500?text=Набор+для+росписи',
      },
      {
        'id': 147,
        'name': 'Пазл 1000 элементов',
        'description': 'Пейзаж, 68x48 см',
        'category': 'hobbiesAndCreativity',
        'price': 899,
        'quantityOfGoods': 18,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Пазл+1000+элементов',
      },
      {
        'id': 148,
        'name': 'Набор для свечей',
        'description': 'Воск, фитили, ароматы',
        'category': 'hobbiesAndCreativity',
        'price': 999,
        'quantityOfGoods': 20,
        'productRating': 4.5,
        'image': 'https://via.placeholder.com/500?text=Набор+для+свечей',
      },
      {
        'id': 149,
        'name': 'Гипсовые барельефы',
        'description': 'Набор для творчества',
        'category': 'hobbiesAndCreativity',
        'price': 799,
        'quantityOfGoods': 25,
        'productRating': 4.2,
        'image': 'https://via.placeholder.com/500?text=Гипсовые+барельефы',
      },
      {
        'id': 150,
        'name': 'Набор для вышивания бисером',
        'description': 'Схема, бисер, канва',
        'category': 'hobbiesAndCreativity',
        'price': 1199,
        'quantityOfGoods': 16,
        'productRating': 4.7,
        'image': 'https://via.placeholder.com/500?text=Набор+для+вышивания+бисером',
      },
      {
        'id': 151,
        'name': 'Детский синтезатор',
        'description': '37 клавиш, микрофон',
        'category': 'hobbiesAndCreativity',
        'price': 2499,
        'quantityOfGoods': 9,
        'productRating': 4.3,
        'image': 'https://via.placeholder.com/500?text=Детский+синтезатор',
      },
      {
        'id': 152,
        'name': 'Набор для квиллинга',
        'description': 'Бумага, инструменты',
        'category': 'hobbiesAndCreativity',
        'price': 699,
        'quantityOfGoods': 28,
        'productRating': 4.4,
        'image': 'https://via.placeholder.com/500?text=Набор+для+квиллинга',
      },
    ]
  },
];

const categoryItems = [
  {
    id: 1,
    type: 'clothesAndShoes',
    name: 'Одежда и обувь',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046852.png',
  },
  {
    id: 2,
    type: 'householdGoods',
    name: 'Товары для дома',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046857.png',
  },
  {
    id: 3,
    type: 'electronics',
    name: 'Электроника',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046858.png',
  },
  {
    id: 4,
    type: 'householdAppliances',
    name: 'Бытовая техника',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046859.png',
  },
  {
    id: 5,
    type: 'goodsForChildren',
    name: 'Товары для детей',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046860.png',
  },
  {
    id: 6,
    type: 'constructionAndRenovation',
    name: 'Стройка и ремонт',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046861.png',
  },
  {
    id: 7,
    type: 'furniture',
    name: 'Мебель',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046862.png',
  },
  {
    id: 8,
    type: 'pharmacy',
    name: 'Аптека',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046867.png',
  },
  {
    id: 9,
    type: 'hobbiesAndCreativity',
    name: 'Хобби и творчество',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046864.png',
  },
];

module.exports = {
  productList,
  categoryItems
}
